load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "database",
    srcs = ["db.go"],
    importpath = "ai-news-agent/internal/database",
    visibility = ["//:__subpackages__"],
    deps = [
        "@com_github_glebarez_sqlite//:sqlite",
        "@io_gorm_gorm//:gorm",
        "@io_gorm_gorm//logger",
    ],
)

go_test(
    name = "database_test",
    srcs = ["db_test.go"],
    embed = [":database"],
)
