load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "crawler",
    srcs = ["crawler.go"],
    importpath = "ai-news-agent/internal/crawler",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/database",
        "@com_github_mmcdole_gofeed//:gofeed",
        "@com_github_puerkitobio_goquery//:goquery",
        "@io_gorm_gorm//:gorm",
    ],
)
