name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/coverage.svg"
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Bazel Setup
        uses: bazelbuild/setup-bazelisk@v3

      - name: Mount bazel cache
        uses: actions/cache@v4
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            bazel-${{ runner.os }}-

      - name: "Test Workspace"
        run: bazel test //...

      - name: "Build Cloud Run Container Binaries & Hugo Documentation"
        run: |
          bazel build //cmd/mcp-server:mcp-server //cmd/mcp-server:mcp_server_linux_amd64 //cmd/mcp-server:mcp_server_linux_arm64 //cmd/mcp-server:pkg_mcp_linux_amd64 //cmd/a2a-agent:a2a-agent //cmd/a2a-agent:a2a_agent_linux_amd64 //cmd/a2a-agent:a2a_agent_linux_arm64 //cmd/a2a-agent:pkg_a2a_agent_linux_amd64 //docs:docs

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bazel Setup
        uses: bazelbuild/setup-bazelisk@v3

      - name: Build Cloud Run Distribution Artifacts
        run: |
          mkdir release
          bazel build //cmd/mcp-server:pkg_mcp_linux_amd64 //cmd/a2a-agent:pkg_a2a_agent_linux_amd64
          cp $(bazel cquery //cmd/mcp-server:pkg_mcp_linux_amd64 --output=files) release/
          cp $(bazel cquery //cmd/a2a-agent:pkg_a2a_agent_linux_amd64 --output=files) release/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "release-${{ github.sha }}"
          files: |
            release/*.tar.gz
          generate_release_notes: true
